apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp-argo-app2
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/alexey-obrezkin-ah/argo-test.git'
        revision: HEAD
        files:
          - path: appsets/*.yaml
  template:
    # An Argo CD Application template, with support for parameter substitution
    # with values from parameters generated above.
    metadata:
      name: "{{name}}"
    spec:
      project: default
      sources:
        - repoURL: https://charts.bitnami.com/bitnami
          chart: nginx
          targetRevision: 13.1.5
          helm:
            releaseName: nginx
            valueFiles:
              - $values/{{helmPath}}/values.yaml
        - repoURL: 'https://github.com/alexey-obrezkin-ah/argo-test.git'
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true